### ISSUE TITLE
exceptions.ProbeError should return original error message

### ISSUE THREAD

**Issue by acarpi** [Apstra/aeon-ztps#143]
In bootstrap scripts, when we try to connect to the box after a given init-delay, I got the following error

```
2017-01-20 22:18:58,107:INFO:172.20.197.7:bootstrap init-delay: 5 seconds
2017-01-20 22:19:03,165:INFO:172.20.197.7:Waiting for device access
2017-01-20 22:19:16,486:INFO:172.20.197.7:rc=1 stdout=
2017-01-20 22:19:16,486:ERROR:172.20.197.7:stderr=Traceback (most recent call last):
  File "/opt/aeonztps/bin/cumulus-bootstrap", line 434, in <module>
    main()
  File "/opt/aeonztps/bin/cumulus-bootstrap", line 424, in main
    dev = wait_for_device(countdown=g_cli_args.reload_delay, poll_delay=10, msg='Waiting for device access')
  File "/opt/aeonztps/bin/cumulus-bootstrap", line 184, in wait_for_device
    timeout=poll_delay)
  File "/usr/local/lib/python2.7/dist-packages/aeon/cumulus/device.py", line 37, in __init__
    self.probe(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/aeon/cumulus/device.py", line 46, in probe
    raise exceptions.ProbeError()
aeon.exceptions.ProbeError
```

Now, ProbeError can be raised for multiple reasons
- connection timeout (e.g. box is not up within a given time)
- connection refused (box doesn't have ssh service up)
- no route to host
- ...

I noticed under the hood the code is relying on socket.connect to check if the box is online, but the original exception message is lost. This would be a useful source of information for debugging.

```
    def probe(self, **kwargs):
        timeout = kwargs.get('timeout') or self.DEFAULT_PROBE_TIMEOUT
        ok, elapsed = probe(self.target, protocol='ssh', timeout=timeout)
        if not ok:
            raise exceptions.ProbeError()
```

**Comment by bobbywatson3** [comment]
I've moved this over to the aeon-venos repo since this bug relates to that codebase.

**Comment by jeremyschulman** [comment]
I can fix this, as part of some other code enhancement I have in process.
