### ISSUE TITLE
[Cumulus bootstrap] on Mellanox, bootstrap script fails due to parsing error

### ISSUE THREAD

**Issue by acarpi** [Apstra/aeon-ztps#162]
Stacktrace from bootstrap.log

```
Traceback (most recent call last):
 File "/opt/aeonztps/bin/cumulus-bootstrap", line 435, in <module>
   main()
 File "/opt/aeonztps/bin/cumulus-bootstrap", line 425, in main
   dev = wait_for_device(countdown=g_cli_args.reload_delay, poll_delay=10, msg='Waiting for device access')
 File "/opt/aeonztps/bin/cumulus-bootstrap", line 185, in wait_for_device
   timeout=poll_delay)
 File "/usr/local/lib/python2.7/dist-packages/aeon/cumulus/device.py", line 40, in __init__
   self.gather_facts()
 File "/usr/local/lib/python2.7/dist-packages/aeon/cumulus/device.py", line 92, in gather_facts
   facts['vendor'] = decoded['Vendor Name']
```

Error is probably due to missing key in decoded-syseeprom output, which for Mellanox looks like this
```
TLV Name             Code Len Value
-------------------- ---- --- -----
Product Name         0x21  64 MSN2100
Part Number          0x22  20 MSN2100-CB2F
Serial Number        0x23  24 MT1651X07617
Base MAC Address     0x24   6 24:8A:07:83:1F:00
Manufacture Date     0x25  19 02/01/2017 14:43:43
Device Version       0x26   1 0
MAC Addresses        0x2A   2 128
Manufacturer         0x2B   8 Mellanox
Vendor Extension     0xFD  36 0x00 0x00 0x81 0x19 0x00 0x12 0x00 0x01 0x06 0x85 0x00 0x00 0x00 0x46 0x00 0x00 0x08 0x00 0x05 0x05 0x05 0x05 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
Platform Name        0x28  64 x86_64-mlnx_x86-r0
ONIE Version         0x29  32 5.0.1404
CRC-32               0xFE   4 0xC6BA4902
```

**Comment by bobbywatson3** [comment]
This was resolved in aeon-venos 0.3.3
