### ISSUE TITLE
mac_address missing in device facts for vEOS

### ISSUE THREAD

**Issue by acarpi** [Apstra/aeon-ztps#195]
Hi,

I haven't verified yet for physical appliances, but at least for virtual EOS I see device facts missing, as such using this field for 'match' rules in os-selector.cfg is returning a KeyError

```
executing 'finally' script:[pid=2025] /opt/aeonztps/etc/profiles/eos/finally -t 172.20.231.13 -s 172.20.231.4:8080 -u AEON_TUSER -p AEON_TPASSWD -l /var/log/aeon-ztp/bootstrapper.log -f '{"os_name": "eos", "ip_addr": "172.20.231.13", "updated_at": "2017-04-10T00:45:30.269785", "image_name": "0", "virtual": true, "hw_model": "vEOS", "vendor": "arista", "message": "bootstrap completed OK", "hw_part_version": null, "hw_version": "", "hw_part_number": null, "created_at": "2017-04-10T00:43:44.896673", "hostname": "localhost", "fqdn": "localhost.dc1.apstra.com", "chassis_id": null, "finally_script": "finally", "os_version": "4.16.6M", "state": "DONE", "serial_number": "525400C8DC22", "os": "eos"}'


2017-04-09 23:37:48,826:ERROR:172.20.231.9:stderr=Traceback (most recent call last):
  File "/opt/aeonztps/bin/aztp_os_selector.py", line 208, in <module>
    main()
  File "/opt/aeonztps/bin/aztp_os_selector.py", line 161, in main
    hw_match = match_hw_model(dev_data, cfg_data)
  File "/opt/aeonztps/bin/aztp_os_selector.py", line 97, in match_hw_model
    if dev_data[fact_key] not in str(fact_value):
KeyError: 'mac_address'
Unable to load os-select output as JSON:
```

This is the os-selector.cfg file I'm using
```
default:
    exact_match: 4.16.6M
    image: EOS-4.16.6M.swi
    finally: finally
profile_spine2:
  matches:
    mac_address:
        - AABBCCDDEEFF
  exact_match: 4.16.6M
  image: EOS-4.16.6M.swi
  finally: finally

```

**Comment by bobbywatson3** [comment]
This issue is resolved in Apstra/aeon-venos#21
